[project]
name = "langchain-basic"
version = "0.1.0"
description = "Veru basic for begginer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.2.10",
    "langchain-core>=1.2.15",
    "langchain-openai>=1.1.10",
    "load-dotenv>=0.1.0",
    "pydantic>=2.12.5",
]
